# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rubocop-modularization` gem.
# Please instead update this file by running `bin/tapioca gem rubocop-modularization`.

module RuboCop; end
module RuboCop::Cop; end
module RuboCop::Cop::Modularization; end

class RuboCop::Cop::Modularization::ClassMethodsAsPublicApis < ::RuboCop::Cop::Base
  def on_def(node); end
end

class RuboCop::Cop::Modularization::NamespacedUnderPackageName < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::RangeHelp

  sig { void }
  def on_new_investigation; end

  sig { returns(T::Boolean) }
  def support_autocorrect?; end

  private

  sig { returns(RuboCop::Cop::Modularization::NamespacedUnderPackageName::DesiredZeitwerkApi) }
  def desired_zeitwerk_api; end

  sig { returns(T::Hash[String, String]) }
  def namespaces_to_packs; end
end

class RuboCop::Cop::Modularization::NamespacedUnderPackageName::DesiredZeitwerkApi
  sig { params(relative_filename: String, package_for_path: ParsePackwerk::Package).returns(T.nilable(RuboCop::Cop::Modularization::NamespacedUnderPackageName::DesiredZeitwerkApi::NamespaceContext)) }
  def for_file(relative_filename, package_for_path); end

  sig { params(pack: ParsePackwerk::Package).returns(String) }
  def get_pack_based_namespace(pack); end

  private

  sig { params(remaining_file_path: String, package_name: String).returns(String) }
  def get_actual_namespace(remaining_file_path, package_name); end

  sig { params(pack: ParsePackwerk::Package).returns(String) }
  def get_package_last_name(pack); end

  sig { returns(Pathname) }
  def root_pathname; end
end

class RuboCop::Cop::Modularization::NamespacedUnderPackageName::DesiredZeitwerkApi::NamespaceContext < ::T::Struct
  const :current_namespace, String
  const :expected_filepath, String
  const :expected_namespace, String

  class << self
    def inherited(s); end
  end
end

class RuboCop::Cop::Modularization::TypedPublicApi < ::RuboCop::Cop::Sorbet::StrictSigil; end
module RuboCop::Modularization; end
RuboCop::Modularization::CONFIG = T.let(T.unsafe(nil), Hash)
RuboCop::Modularization::CONFIG_DEFAULT = T.let(T.unsafe(nil), Pathname)
class RuboCop::Modularization::Error < ::StandardError; end

module RuboCop::Modularization::Inject
  class << self
    sig { void }
    def defaults!; end
  end
end

RuboCop::Modularization::PROJECT_ROOT = T.let(T.unsafe(nil), Pathname)
module RuboCop::Modularization::Private; end
