# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::RuboCop::Cop::PackageProtections::NamespacedUnderPackageName; end
module ::RuboCop::RSpec::ExpectOffense; end
module RSpec::Matchers; end

class Hash
  def to_yaml; end
end
