# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::Zeitwerk::Loader; end
module RSpec::Matchers; end
module RuboCop::RSpec::ExpectOffense; end
class Hash
  def to_yaml; end
end
